In [0]:
import numpy as np

In [13]:
a = np.array([2,3,4,4])

print(a[-2:])

#b = a[-2:]
#type(b)

c = np.zeros((2,4)) #2-by-4
print(c)

[4 4]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
d = np.random.random((2,3))
print(d)

[[0.08510506 0.07993252 0.17773447]
 [0.7407135  0.51283381 0.16962208]]


In [17]:
print(d[:,1])#First column => 0.07993252, 0.51283381
print(d[0,1]) 
print(d[0][1])

[0.07993252 0.51283381]
0.07993251782126742
0.07993251782126742


In [18]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# adding
x + y

x * y

x = np.array([1,2,3])
y = np.array([5,3,5])

# Dot product of vectors x and y 
c = np.dot(x,y)
print(c)

26


In [22]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
#Sum the first row of x and y. Return vectors
x.sum(axis = 0)

[[1. 2.]
 [3. 4.]]


array([4., 6.])